#!/usr/bin/env bash

## Aliases

hc_chain() {
	CHAINED="$CHAINED ! $@"
}
hc_run_chain() {
	herbstclient chain "!" $CHAINED
}

hc() {
	hc_chain "$@"
}
keybind() {
	hc_chain keybind "$@"
}

mousebind() {
	hc_chain mousebind "$@"
}

## Startup

# Emit custom reload hook.
hc emit_hook reload

# Remove all keybinds, mousebinds and rules.
hc keyunbind   --all
hc mouseunbind --all
hc unrule -F

# Basic keybinds.

MOD="Mod4" # Super key.

# Quit and reload. Yay.
keybind $MOD-Shift-e         quit
keybind $MOD-Shift-r         reload

# Window operation keybindings and settings.
keybind $MOD-Shift-q         close

keybind $MOD-Left            focus left
keybind $MOD-h               focus left
keybind $MOD-Down            focus down
keybind $MOD-j               focus down
keybind $MOD-Up              focus up
keybind $MOD-k               focus up
keybind $MOD-Right           focus right
keybind $MOD-l               focus right

keybind $MOD-Shift-Left      shift left
keybind $MOD-Shift-a         shift left
keybind $MOD-Shift-Down      shift down
keybind $MOD-Shift-s         shift down
keybind $MOD-Shift-Up        shift up
keybind $MOD-Shift-w         shift up
keybind $MOD-Shift-Right     shift right
keybind $MOD-Shift-d         shift right

RZSTEP="0.05"
keybind $MOD-Control-Left    resize left  +$RZSTEP
keybind $MOD-Control-a       resize left  +$RZSTEP
keybind $MOD-Control-Down    resize down  +$RZSTEP
keybind $MOD-Control-s       resize down  +$RZSTEP
keybind $MOD-Control-Up      resize up    +$RZSTEP
keybind $MOD-Control-w       resize up    +$RZSTEP
keybind $MOD-Control-Right   resize right +$RZSTEP
keybind $MOD-Control-d       resize right +$RZSTEP

# Frames and layouts.
keybind $MOD-Control-space   split explode
keybind $MOD-b               split bottom 0.5
keybind $MOD-v               split right  0.5
keybind $MOD-n               remove

keybind $MOD-Shift-f			floating toggle
keybind $MOD-Shift-space		fullscreen toggle
keybind $MOD-Shift-p			pseudotile toggle
keybind $MOD-Shift-s			cycle_layout +1 vertical horizontal grid
keybind $MOD-Shift-v			set_layout vertical
keybind $MOD-Shift-h			set_layout horizontal
keybind $MOD-Shift-g			set_layout grid

# Tags.
# Logic plain stolen from nxll. Many thanks.
tag_names=( {I,II,III,IV,V,VI,VII} )
tag_keys=( {1..7} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
	hc add "${tag_names[$i]}"
	key="${tag_keys[$i]}"
	if ! [ -z "$key" ] ; then
		keybind "$MOD-$key" use_index "$i"
		keybind "$MOD-Shift-$key" move_index "$i"
	fi
done

# Tag keybinds.
keybind $MOD-bracketright    use_index +1 --skip-visible
keybind $MOD-bracketleft     use_index -1 --skip-visible

# Mouse.
hc set focus_follows_mouse 1
mousebind $MOD-Button1       move
mousebind $MOD-Button2       zoom
mousebind $MOD-Button3       resize

# Focus.
keybind $MOD-BackSpace       cycle_monitor
keybind $MOD-Tab             cycle_all +1
keybind $MOD-Shift-Tab       cycle_all -1
keybind $MOD-c               cycle
keybind $MOD-u               jumpto urgent

# Rules.
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=Oblogout fullscreen=on
hc rule class=Engrampa fullscreen=on
#hc rule instance=gl  pseudotile=on


# Theming.
# More or less stolen from nxll, as well.
#hc attr theme.tiling.reset         1
#hc attr theme.floating.reset       1
hc pad 0 0 0 26
hc set frame_border_active_color    '#b800e6'
hc set frame_border_normal_color    '#070000'
hc set frame_bg_normal_color        '#cc3300'
hc set frame_bg_active_color        '#070000'
hc set frame_border_width           0
hc set always_show_frame            0
hc set frame_bg_transparent         1
hc set frame_transparent_width      0
hc set frame_gap                    4
hc attr theme.active.color          '#373737'
hc attr theme.normal.color          '#808080'
hc attr theme.urgent.color          '#939490'
hc attr theme.inner_width           1
hc attr theme.outer_width           0
hc attr theme.inner_color           '#373737'
hc attr theme.border_width          4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width  0
hc attr theme.floating.inner_width  1
hc attr theme.floating.inner_color  '#373737'
hc attr theme.floating.outer_color  '#373737'
hc attr theme.active.inner_color    '#373737'
hc attr theme.active.outer_color    '#373737'
hc attr theme.normal.inner_color    '#373737'
hc attr theme.normal.outer_color    '#373737'
hc attr theme.background_color      '#373737'
hc set window_gap                   4
hc set frame_padding                0
hc set smart_window_surroundings    0
hc set smart_frame_surroundings     0
hc set mouse_recenter_gap           0

hc set tree_style '╾│ ├└╼─┐'

# App Launch
hc keybind $MOD-Insert					spawn scrot
hc keybind $MOD-d 						spawn rofi -show drun
hc keybind $MOD-t 						spawn rofi -show run
hc keybind $MOD-F7 						spawn light -A 10.00
hc keybind $MOD-F6 						spawn light -U 10.00
hc keybind XF86MonBrightnessDown 		spawn light -U 10.00
hc keybind $MOD-Return 					spawn lxterminal
hc keybind XF86AudioRaiseVolume 		spawn pamixer -i 10
hc keybind XF86AudioLowerVolume 		spawn pamixer -d 10
hc keybind XF86AudioMute				spawn pamixer -t
hc keybind $MOD-Delete 					spawn oblogout
keybind $MOD-Shift-q 					close
hc keybind $MOD-p 						spawn clipmenu
##
# Host specific config
##

HOST=`hostname`
[ -f ~/.config/herbstluftwm/hosts/$HOST ] && . ~/.config/herbstluftwm/hosts/$HOST

##
# FINISH LINE
##

# Detect monitors.
hc detect_monitors

# Unlock...
hc unlock

# and run chain.
hc_run_chain

#autostart
./startup &